<?php
/**
 * Copyright (c) 2018 CardGate B.V.
 * All rights reserved.
 * See LICENSE for license details.
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?> by
        <a href="https://www.cardgate.com/">CardGate</a></dt>
<?php
    // NOTE when the order is mailed the transaction has not yet been registered and there's no cardgate transaction
    // id yet. When the invoice is sent, there is, so it gets included.
    $sTransactionId = $escaper->escapeHtml($block->getInfo()->getCardgateTransaction());
if (! empty($sTransactionId)) {
    ?>
    <dd class="content">
        <strong><?= $escaper->escapeHtml(__('Transaction ID')) ?></strong>
        <span class="number"><?= $escaper->escapeHtml($block->getInfo()->getCardgateTransaction()) ?></span>
    </dd>
    <?php
}
?>
    <?php if ($block->getInstructions()):?>
        <dd class="content"><?= $escaper->escapeHtml(nl2br($block->getInstructions())) ?></dd>
    <?php endif; ?>
</dl>
