<?php
/**
 * Copyright (c) 2018 CardGate B.V.
 * All rights reserved.
 * See LICENSE for license details.
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?> by CardGate</dt>
    <dt class="content">
        <strong><?= $block->escapeHtml(__('Transaction ID')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getCardgateTransaction()) ?></span>
    </dt>
    <?php if ($block->getInstructions()) : ?>
        <dt class="content"><?= nl2br($block->escapeHtml($block->getInstructions())) ?></dt>
    <?php endif; ?>
</dl>
